version: "3"

services:
  mongodb:
    image: mongo:3.2
    # We use WiredTiger in all environments. In development environments we use small files
    # to conserve disk space, and disable the journal for a minor performance gain.
    # See https://docs.mongodb.com/v3.0/reference/program/mongod/#options for complete details.
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1080:1080"

  redis:
    image: redis:4-alpine

  xapi:
    image: learninglocker/xapi-service:2.2.14
    environment:
      - MONGO_URL=mongodb://mongodb:27017/learninglocker_v2
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
      - api
      - ui
      - worker

  api:
    image: fundocker/learninglocker:v2.6.2
    env_file:
      - env.d/learninglocker
    expose:
      - "8080"
    command: "node api/dist/server"
    depends_on:
      - mongodb
      - redis
      - mailcatcher

  ui:
    image: fundocker/learninglocker:v2.6.2
    env_file:
      - env.d/learninglocker
    expose:
      - "3000"
    command: "node ui/dist/server"
    depends_on:
      - mongodb
      - redis
      - api

  worker:
    image: fundocker/learninglocker:v2.6.2
    env_file:
      - env.d/learninglocker
    command: "node worker/dist/server"
    depends_on:
      - mongodb
      - redis
      - mailcatcher

  nginx:
    image: nginx:1.15
    env_file:
      - env.d/nginx
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - ui
      - xapi
    ports:
      - "8080:80"
